services:
  db:
    volumes:
      - ./datastore/mysql:/var/lib/mysql

  azfin-backend:
    volumes:
      - ./datastore/uploads:/app/uploads
    ports:
      - "3002:3001"

  azfin-frontend:
    ports:
      - "901:901"

  phpmyadmin:
    ports:
      - "8081:80"

networks:
  edge:
    external: false
    name: azfin-local-edge
